
import random
from datetime import datetime, timedelta

especialidades = ['Calistenia',
                    'Treino de força',
                    'Treino de tensão mecânica',
                    'Treino metabólico',
                    'Treino de condicionamento'
                    ]


def random_datetime(start, end):
    delta = end - start
    random_seconds = random.randint(0, int(delta.total_seconds()))
    return start + timedelta(seconds=random_seconds)

start_date = datetime(2020, 1, 1)
end_date = datetime(2023, 12, 31)

random_date = random_datetime(start_date, end_date)

diet_meals = [
    "Salada de frango com quinoa",
    "Omelete de claras com espinafre",
    "Smoothie de frutas vermelhas com proteína",
    "Sopa de legumes",
    "Peito de frango grelhado com brócolis",
    "Iogurte grego com mel e nozes",
    "Salmão grelhado com aspargos",
    "Wrap de alface com atum",
    "Arroz integral com peito de peru",
    "Abacate recheado com atum",
    "Sanduíche de pão integral com peito de peru",
    "Quinoa com legumes assados",
    "Tapioca com queijo cottage",
    "Peixe grelhado com batata-doce",
    "Cuscuz marroquino com frango",
    "Macarrão integral com molho de tomate caseiro",
    "Crepioca de frango desfiado",
    "Sopa de abóbora com gengibre",
    "Salada de grão-de-bico com atum",
    "Panqueca de aveia com banana",
    "Bowl de açaí com granola",
    "Torta de frango low carb",
    "Tilápia grelhada com espinafre",
    "Sushi de pepino com salmão",
    "Salada caprese com frango",
    "Sanduíche de peito de frango com abacate",
    "Batata-doce recheada com frango desfiado",
    "Cenoura e pepino com húmus",
    "Hambúrguer de quinoa com abacate",
    "Sopa de lentilha com espinafre",
    "Salada de frutas com chia",
    "Mingau de aveia com frutas",
    "Wrap de peito de peru com salada",
    "Tapioca com peito de peru",
    "Espetinho de frango com legumes",
    "Almôndegas de frango com molho de tomate",
    "Ceviche de peixe branco",
    "Arroz de couve-flor com carne moída",
    "Panqueca de claras com morangos",
    "Pizza de abobrinha com frango",
    "Quinoa com grão-de-bico e legumes",
    "Bolinho de batata-doce com atum",
    "Sopa de tomate com manjericão",
    "Salada de rúcula com queijo cottage",
    "Wrap de frango grelhado com pimentão",
    "Macarrão de abobrinha com molho pesto",
    "Omelete de espinafre com queijo branco",
    "Salada de lentilha com cenoura",
    "Crepioca de ricota com espinafre",
    "Tartar de salmão com abacate",
    "Peito de frango com legumes grelhados",
    "Iogurte natural com sementes de chia",
    "Sopa de ervilha com hortelã",
    "Salada de quinoa com camarão",
    "Couve refogada com frango desfiado",
    "Espaguete de abóbora com molho de tomate",
    "Bolo de banana sem açúcar",
    "Bowl de salada com atum e ovo cozido",
    "Salada de rúcula com figos e nozes",
    "Muffin de aveia com cenoura",
    "Tilápia grelhada com couve-flor",
    "Quiche de legumes sem massa",
    "Wrap de salmão defumado com alface",
    "Sopa de couve-flor com alho-poró",
    "Salada de repolho com cenoura e atum",
    "Torrada integral com abacate e ovo poché",
    "Panqueca de batata-doce com frango",
    "Espetinho de camarão com pimentão",
    "Salmão ao forno com espinafre",
    "Hambúrguer de frango com salada verde",
    "Omelete de atum com tomate",
    "Abobrinha recheada com carne moída",
    "Bowl de quinoa com vegetais assados",
    "Salada de pepino com molho de iogurte",
    "Wrap de frango com guacamole",
    "Sopa de cenoura com gengibre",
    "Salada de grão-de-bico com tomate",
    "Creme de abacate com cacau",
    "Salada de alface com tomate e ovo cozido",
    "Tilápia assada com legumes",
    "Sanduíche de atum com pão integral",
    "Salada de espinafre com amêndoas",
    "Omelete de claras com cogumelos",
    "Cuscuz de quinoa com vegetais",
    "Salada de quinoa com peito de frango",
    "Sopa de batata-doce com frango",
    "Sashimi de salmão com salada",
    "Sanduíche de peito de frango com rúcula",
    "Macarrão integral com molho de pesto",
    "Crepioca de banana com canela",
    "Hambúrguer de atum com salada",
    "Wrap de quinoa com legumes",
    "Bowl de iogurte com frutas vermelhas",
    "Tilápia com quinoa e espinafre",
    "Salada de pepino com molho de gergelim",
    "Couve refogada com quinoa",
    "Frango grelhado com salada de espinafre",
    "Sopa de abobrinha com hortelã"
]

exerciciosh = {
    "Agachamento": "Pernas",
    "Flexão de Braços": "Peito, Tríceps, Ombros",
    "Abdominal": "Abdômen",
    "Pular Corda": "Cardio, Pernas",
    "Corrida": "Cardio, Pernas",
    "Bicicleta": "Cardio, Pernas",
    "Remada": "Costas, Bíceps",
    "Levantamento Terra": "Pernas, Costas, Glúteos",
    "Supino": "Peito, Tríceps, Ombros",
    "Puxada na Barra Fixa": "Costas, Bíceps",
    "Tríceps na Polia": "Tríceps",
    "Rosca Direta": "Bíceps",
    "Desenvolvimento com Halteres": "Ombros, Tríceps",
    "Stiff": "Pernas, Glúteos, Costas",
    "Leg Press": "Pernas",
    "Cadeira Extensora": "Quadríceps",
    "Cadeira Flexora": "Isquiotibiais",
    "Elevação de Panturrilhas": "Panturrilhas",
    "Puxada na Frente": "Costas, Bíceps",
    "Barra Fixa com Pegada Supinada": "Costas, Bíceps",
    "Abdominal na Bola Suíça": "Abdômen",
    "Mountain Climbers": "Cardio, Abdômen, Pernas",
    "Burpees": "Cardio, Pernas, Peito, Abdômen",
    "Kettlebell Swing": "Pernas, Glúteos, Costas",
    "Box Jump": "Pernas, Glúteos",
    "Puxada Alta": "Costas, Ombros",
    "Lunge": "Pernas, Glúteos",
    "Flexão de Braços com Abertura": "Peito, Tríceps, Ombros",
    "Plank": "Abdômen, Core",
    "Pistol Squat": "Pernas, Glúteos",
    "Hollow Body Hold": "Abdômen",
    "Jumping Jacks": "Cardio, Pernas, Ombros",
    "Sit-ups": "Abdômen",
    "Russian Twists": "Abdômen, Oblíquos",
    "Bicep Curl com Halteres": "Bíceps",
    "Tríceps Dips": "Tríceps, Peito",
    "Pull-ups": "Costas, Bíceps",
    "Push Press": "Ombros, Tríceps, Pernas",
    "Deadlifts com Halteres": "Pernas, Costas, Glúteos",
    "Renegade Rows": "Costas, Bíceps, Abdômen",
    "Box Squats": "Pernas, Glúteos",
    "Single-leg Deadlifts": "Pernas, Glúteos, Costas",
    "Decline Bench Press": "Peito, Tríceps, Ombros",
    "Incline Bench Press": "Peito, Tríceps, Ombros",
    "Tríceps com Halteres": "Tríceps",
    "Russian Kettlebell Swings": "Pernas, Glúteos, Costas",
    "Sprints": "Cardio, Pernas",
    "Skipping": "Cardio, Pernas",
    "Agachamento com Salto": "Pernas, Glúteos",
    "Caminhada em Subida": "Cardio, Pernas, Glúteos"
}

