"""tables changes on user

Revision ID: 04a8876ee579
Revises: b64a895a5c26
Create Date: 2024-08-30 21:49:32.032645

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '04a8876ee579'
down_revision = 'b64a895a5c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
