"""changes

Revision ID: 0879583c9645
Revises: b9b1cb9e66ab
Create Date: 2024-08-30 20:25:12.986965

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0879583c9645'
down_revision = 'b9b1cb9e66ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treinador',
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('especialidade', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.ForeignKeyConstraint(['telefone'], ['telefone.telefone'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.alter_column('telefone', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telefone', 'telefone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=11),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_table('treinador')
    # ### end Alembic commands ###
