"""Add column last_name to User model21

Revision ID: 1c7ced18cb52
Revises: 77dceb3948e3
Create Date: 2024-09-09 09:59:41.551671

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c7ced18cb52'
down_revision = '77dceb3948e3'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TABLE plano;")
    op.execute("DROP TABLE dieta_refeicoes;")
    op.execute("DROP TABLE dieta;")
    op.execute("DROP TABLE refeicao;")
    op.execute("DROP TABLE avaliacao;")
    op.execute("DROP TABLE shape;")
    op.execute("DROP TABLE treinador_telefones;")
    op.execute("DROP TABLE treinador;")
    op.execute("DROP TABLE telefone;")
    op.execute("DROP TABLE treino_sessao;")
    op.execute("DROP TABLE treino_exercicio;")
    op.execute("DROP TABLE sessao;")
    op.execute("DROP TABLE treino;")
    op.execute("DROP VIEW exercicios_com_pernas")
    op.execute("DROP VIEW exercicios_cardio")
    op.execute("DROP VIEW exercicios_por_grupo")
    op.execute("DROP TABLE exercicio;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('treinador_telefone_fkey', 'treinador', 'telefone', ['telefone'], ['telefone'])
    op.create_table('treinador_telefones',
    sa.Column('treinador_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('telefone_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['telefone_id'], ['telefone.telefone'], name='treinador_telefones_telefone_id_fkey'),
    sa.ForeignKeyConstraint(['treinador_id'], ['treinador.id'], name='treinador_telefones_treinador_id_fkey'),
    sa.PrimaryKeyConstraint('treinador_id', 'telefone_id', name='treinador_telefones_pkey')
    )
    op.create_table('telefone',
    sa.Column('telefone', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telefone', name='telefone_pkey')
    )
    op.drop_table('treinador_locais')
    op.drop_table('local')
    # ### end Alembic commands ###
