"""shapes

Revision ID: 2343b677617f
Revises: 94b2de5ec7e0
Create Date: 2024-09-03 20:37:12.478655

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2343b677617f'
down_revision = '94b2de5ec7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
