"""Add

Revision ID: 252d0468f2c2
Revises: cb73b46e7266
Create Date: 2024-08-29 12:39:34.622716

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '252d0468f2c2'
down_revision = 'cb73b46e7266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treinador')
    op.drop_table('telefone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telefone',
    sa.Column('telefone', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telefone', name='telefone_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('treinador',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('especialidade', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['telefone'], ['telefone.telefone'], name='treinador_telefone_fkey'),
    sa.PrimaryKeyConstraint('id', name='treinador_pkey')
    )
    # ### end Alembic commands ###
