"""sessao

Revision ID: 27aa2657a3d5
Revises: 8e2a823c854b
Create Date: 2024-09-07 19:07:11.004184

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '27aa2657a3d5'
down_revision = '8e2a823c854b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
