"""fks

Revision ID: 28fe8426e6e3
Revises: b55def56e8c1
Create Date: 2024-09-07 02:16:18.986381

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '28fe8426e6e3'
down_revision = 'b55def56e8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
