"""sessao

Revision ID: 2d70bdff42c8
Revises: 27aa2657a3d5
Create Date: 2024-09-07 19:21:02.322018

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2d70bdff42c8'
down_revision = '27aa2657a3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treino', sa.Column('calorias', sa.Integer(), nullable=False))
    op.drop_constraint('treino_id_exercicio_fkey', 'treino', type_='foreignkey')
    op.drop_column('treino', 'id_exercicio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treino', sa.Column('id_exercicio', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('treino_id_exercicio_fkey', 'treino', 'exercicio', ['id_exercicio'], ['id'])
    op.drop_column('treino', 'calorias')
    # ### end Alembic commands ###
