"""fks

Revision ID: 3b5b5fdd8c0e
Revises: 28fe8426e6e3
Create Date: 2024-09-07 02:40:34.393733

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b5b5fdd8c0e'
down_revision = '28fe8426e6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
