"""repopulating

Revision ID: 411798093048
Revises: 8f63f74637dc
Create Date: 2024-09-08 04:04:46.371593

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '411798093048'
down_revision = '8f63f74637dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shape',
    sa.Column('nome_foto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('avaliacao', sa.Column('shape_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'avaliacao', 'shape', ['shape_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'avaliacao', type_='foreignkey')
    op.drop_column('avaliacao', 'shape_id')
    op.drop_table('shape')
    # ### end Alembic commands ###
