"""thiago_

Revision ID: 419925848ea3
Revises: 7a9f536722bd
Create Date: 2024-09-03 19:30:53.380047

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '419925848ea3'
down_revision = '7a9f536722bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
