"""fks

Revision ID: 4cdbcb69d86a
Revises: b68517527bfb
Create Date: 2024-09-07 13:43:04.635212

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4cdbcb69d86a'
down_revision = 'b68517527bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treinador_telefones',
    sa.Column('treinador_id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('telefone_id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.ForeignKeyConstraint(['telefone_id'], ['telefone.telefone'], ),
    sa.ForeignKeyConstraint(['treinador_id'], ['treinador.id'], ),
    sa.PrimaryKeyConstraint('treinador_id', 'telefone_id')
    )
    op.create_table('treino_exercicio',
    sa.Column('id_treino', sa.Integer(), nullable=False),
    sa.Column('id_exercicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_exercicio'], ['exercicio.id'], ),
    sa.ForeignKeyConstraint(['id_treino'], ['treino.id'], ),
    sa.PrimaryKeyConstraint('id_treino', 'id_exercicio')
    )
    op.create_table('treino_sessao',
    sa.Column('id_treino1', sa.Integer(), nullable=False),
    sa.Column('id_treino2', sa.Integer(), nullable=False),
    sa.Column('id_treino3', sa.Integer(), nullable=False),
    sa.Column('id_trei', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_trei'], ['sessao.id'], ),
    sa.ForeignKeyConstraint(['id_treino1'], ['treino.id'], ),
    sa.ForeignKeyConstraint(['id_treino2'], ['treino.id'], ),
    sa.ForeignKeyConstraint(['id_treino3'], ['treino.id'], ),
    sa.PrimaryKeyConstraint('id_treino1', 'id_treino2', 'id_treino3', 'id_trei')
    )
    op.add_column('exercicio', sa.Column('grupo_muscular', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('sessao_id_treino_fkey', 'sessao', type_='foreignkey')
    op.drop_column('sessao', 'id_treino')
    op.drop_column('treino', 'grupo_muscular')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treino', sa.Column('grupo_muscular', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sessao', sa.Column('id_treino', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('sessao_id_treino_fkey', 'sessao', 'treino', ['id_treino'], ['id'])
    op.drop_column('exercicio', 'grupo_muscular')
    op.drop_table('treino_sessao')
    op.drop_table('treino_exercicio')
    op.drop_table('treinador_telefones')
    # ### end Alembic commands ###
