"""new models

Revision ID: 510580437425
Revises: a7a83e25c477
Create Date: 2024-09-06 20:33:02.130490

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '510580437425'
down_revision = 'a7a83e25c477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE sessao;DROP TABLE treino; DROP TABLE exercicio;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
