"""unbProject

Revision ID: 5afb2c3787f2
Revises: b9e2936151d7
Create Date: 2024-09-08 05:28:39.912959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5afb2c3787f2'
down_revision = 'b9e2936151d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE item;')
    op.execute('DROP TABLE "user";')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.drop_table('treinador_telefones')
    op.drop_table('plano')
    op.drop_table('treino_sessao')
    op.drop_table('treino_exercicio')
    op.drop_table('treinador')
    op.drop_table('dieta_refeicoes')
    op.drop_table('avaliacao')
    op.drop_table('treino')
    op.drop_table('telefone')
    op.drop_table('shape')
    op.drop_table('sessao')
    op.drop_table('refeicao')
    op.drop_table('exercicio')
    op.drop_table('dieta')
    # ### end Alembic commands ###
