"""tables changes on user

Revision ID: 5d4aae4cfd08
Revises: b1945b39fb15
Create Date: 2024-08-30 21:18:38.687071

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5d4aae4cfd08'
down_revision = 'b1945b39fb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
