"""fks

Revision ID: 5d731f8e36df
Revises: fc8b96cdaadb
Create Date: 2024-09-07 02:03:57.072040

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5d731f8e36df'
down_revision = 'fc8b96cdaadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refeicao', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('refeicao', 'calorias',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refeicao', 'calorias',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('refeicao', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
