"""tables changes on user

Revision ID: 61bb25bc9766
Revises: 5d4aae4cfd08
Create Date: 2024-08-30 21:19:32.090932

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '61bb25bc9766'
down_revision = '5d4aae4cfd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
