"""plano user pk

Revision ID: 77dceb3948e3
Revises: b1b2bd0fb31d
Create Date: 2024-09-08 14:31:13.302975

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77dceb3948e3'
down_revision = 'b1b2bd0fb31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plano_id_dieta_fkey', 'plano', type_='foreignkey')
    op.drop_column('plano', 'id_dieta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plano', sa.Column('id_dieta', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plano_id_dieta_fkey', 'plano', 'dieta', ['id_dieta'], ['id'])
    # ### end Alembic commands ###
