"""updates

Revision ID: 782605f20780
Revises: 9154e446c286
Create Date: 2024-09-03 11:14:02.877700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '782605f20780'
down_revision = '9154e446c286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telefone',
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.PrimaryKeyConstraint('telefone')
    )
    op.create_table('treinador',
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('especialidade', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.ForeignKeyConstraint(['telefone'], ['telefone.telefone'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.drop_table('dieta')
    op.drop_table('refeicao')
    op.add_column('user', sa.Column('birthdate', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False))
    op.create_unique_constraint(None, 'user', ['cpf'])
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'cpf')
    op.drop_column('user', 'name')
    op.drop_column('user', 'birthdate')
    op.create_table('refeicao',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('calorias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('refeicao_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='refeicao_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('dieta',
    sa.Column('id_ref_manha', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_ref_tarde', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_ref_noite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_ref_manha'], ['refeicao.id'], name='dieta_id_ref_manha_fkey'),
    sa.ForeignKeyConstraint(['id_ref_noite'], ['refeicao.id'], name='dieta_id_ref_noite_fkey'),
    sa.ForeignKeyConstraint(['id_ref_tarde'], ['refeicao.id'], name='dieta_id_ref_tarde_fkey'),
    sa.PrimaryKeyConstraint('id', name='dieta_pkey')
    )
    op.drop_table('treinador')
    op.drop_table('telefone')
    # ### end Alembic commands ###
