"""new

Revision ID: 7961c6522bdf
Revises: 935e2ac1519d
Create Date: 2024-09-09 23:42:01.735202

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7961c6522bdf'
down_revision = '935e2ac1519d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
