"""oas

Revision ID: 81ac8f791f7f
Revises: d6486b600d6a
Create Date: 2024-09-08 05:24:50.132826

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '81ac8f791f7f'
down_revision = 'd6486b600d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
