"""lucas changes

Revision ID: 8434edbda2fb
Revises: 0081da563c60
Create Date: 2024-09-03 18:19:47.711298

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8434edbda2fb'
down_revision = '0081da563c60'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TABLE dieta;")
    op.execute("DROP TABLE refeicao;")
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dieta', 'id_ref_manha',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('dieta', 'id_ref_tarde',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('dieta', 'id_ref_noite',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('dieta', 'id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('refeicao', 'id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###
'''

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refeicao', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('dieta', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('dieta', 'id_ref_noite',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('dieta', 'id_ref_tarde',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('dieta', 'id_ref_manha',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
