"""thiago_features

Revision ID: 88ebb388f2d4
Revises: 68ef8596328e
Create Date: 2024-09-03 19:21:57.054895

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '88ebb388f2d4'
down_revision = '68ef8596328e'
branch_labels = None
depends_on = None


def upgrade():
 #   op.execute("DROP TABLE plano;")
#    op.execute('DROP TABLE "user" ;')
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('data_avaliacao', sa.DateTime(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('perc_gordura', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefone',
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.PrimaryKeyConstraint('telefone')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_dieta', sa.Integer(), nullable=True),
    sa.Column('id_sessao_treino', sa.Integer(), nullable=True),
    sa.Column('id_treinador', sa.Integer(), nullable=True),
    sa.Column('id_avaliacao', sa.Integer(), nullable=True),
    sa.Column('local', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treinador',
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('especialidade', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.ForeignKeyConstraint(['telefone'], ['telefone.telefone'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.drop_table('refeicao')
    op.drop_table('dieta')
    op.drop_table('item')
    # ### end Alembic commands ###
'''

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.create_table('dieta',
    sa.Column('id_ref_manha', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id_ref_tarde', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id_ref_noite', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_ref_manha'], ['refeicao.id'], name='dieta_id_ref_manha_fkey'),
    sa.ForeignKeyConstraint(['id_ref_noite'], ['refeicao.id'], name='dieta_id_ref_noite_fkey'),
    sa.ForeignKeyConstraint(['id_ref_tarde'], ['refeicao.id'], name='dieta_id_ref_tarde_fkey'),
    sa.PrimaryKeyConstraint('id', name='dieta_pkey')
    )
    op.create_table('refeicao',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('calorias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='refeicao_pkey')
    )
    op.drop_table('treinador')
    op.drop_table('plano')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('telefone')
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
