"""fotos

Revision ID: 8d4b9f60cbd9
Revises: 419925848ea3
Create Date: 2024-09-03 20:26:51.624362

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8d4b9f60cbd9'
down_revision = '419925848ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shape',
    sa.Column('nome_foto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('nome_foto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shape')
    # ### end Alembic commands ###
