"""fks

Revision ID: 8e2a823c854b
Revises: 4cdbcb69d86a
Create Date: 2024-09-07 15:12:35.811530

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8e2a823c854b'
down_revision = '4cdbcb69d86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treino_sessao', sa.Column('id_sessao', sa.Integer(), nullable=False))
    op.drop_constraint('treino_sessao_id_trei_fkey', 'treino_sessao', type_='foreignkey')
    op.create_foreign_key(None, 'treino_sessao', 'sessao', ['id_sessao'], ['id'])
    op.drop_column('treino_sessao', 'id_trei')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treino_sessao', sa.Column('id_trei', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'treino_sessao', type_='foreignkey')
    op.create_foreign_key('treino_sessao_id_trei_fkey', 'treino_sessao', 'sessao', ['id_trei'], ['id'])
    op.drop_column('treino_sessao', 'id_sessao')
    # ### end Alembic commands ###
