"""repopulating

Revision ID: 8f63f74637dc
Revises: eee403bbe9f1
Create Date: 2024-09-08 04:03:00.107969

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8f63f74637dc'
down_revision = 'eee403bbe9f1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TABLE shape;")
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('avaliacao', sa.Column('shape_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'avaliacao', 'shape', ['shape_id'], ['id'])
    #op.add_column('shape', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shape', 'id')
    op.drop_constraint(None, 'avaliacao', type_='foreignkey')
    op.drop_column('avaliacao', 'shape_id')
    # ### end Alembic commands ###
