"""lucas changes

Revision ID: 9154e446c286
Revises: efe620b59ef0
Create Date: 2024-09-01 23:06:31.119138

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9154e446c286'
down_revision = 'efe620b59ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refeicao',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('calorias', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dieta',
    sa.Column('id_ref_manha', sa.Integer(), nullable=True),
    sa.Column('id_ref_tarde', sa.Integer(), nullable=True),
    sa.Column('id_ref_noite', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ref_manha'], ['refeicao.id'], ),
    sa.ForeignKeyConstraint(['id_ref_noite'], ['refeicao.id'], ),
    sa.ForeignKeyConstraint(['id_ref_tarde'], ['refeicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('treinador')
    op.drop_table('telefone')
    op.add_column('user', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_constraint('user_cpf_key', 'user', type_='unique')
    op.drop_column('user', 'name')
    op.drop_column('user', 'cpf')
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_cpf_key', 'user', ['cpf'])
    op.drop_column('user', 'full_name')
    op.create_table('telefone',
    sa.Column('telefone', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telefone', name='telefone_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('treinador',
    sa.Column('telefone', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('especialidade', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['telefone'], ['telefone.telefone'], name='treinador_telefone_fkey'),
    sa.PrimaryKeyConstraint('id', name='treinador_pkey'),
    sa.UniqueConstraint('telefone', name='treinador_telefone_key')
    )
    op.drop_table('item')
    op.drop_table('dieta')
    op.drop_table('refeicao')
    # ### end Alembic commands ###
