"""newz

Revision ID: 935e2ac1519d
Revises: b499e906e1a0
Create Date: 2024-09-09 23:18:45.278740

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '935e2ac1519d'
down_revision = 'b499e906e1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
