"""fotos

Revision ID: 94b2de5ec7e0
Revises: 8d4b9f60cbd9
Create Date: 2024-09-03 20:30:59.398925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '94b2de5ec7e0'
down_revision = '8d4b9f60cbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE shape;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
