"""treinador

Revision ID: 9ec35cd38fc6
Revises: 03e3d4c7313e
Create Date: 2024-08-30 13:28:07.116038

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ec35cd38fc6'
down_revision = '03e3d4c7313e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
