"""Add column last_name to User model

Revision ID: a469e3e11772
Revises: 0fed7c4021c0
Create Date: 2024-09-06 20:42:44.226447

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a469e3e11772'
down_revision = '0fed7c4021c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
