"""generate models for teusdev

Revision ID: a7a83e25c477
Revises: b5b2a6e31ba3
Create Date: 2024-09-06 19:28:08.905068

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a7a83e25c477'
down_revision = 'b5b2a6e31ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treino',
    sa.Column('id_exercicio', sa.Integer(), nullable=False),
    sa.Column('grupo_muscular', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_exercicio'], ['exercicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'sessao', 'treino', ['id_treino'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessao', type_='foreignkey')
    op.drop_table('treino')
    # ### end Alembic commands ###
