"""newz

Revision ID: a8fc43c35c67
Revises: 236dfd7085d3
Create Date: 2024-09-08 12:03:20.084995

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a8fc43c35c67'
down_revision = '236dfd7085d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
