"""final

Revision ID: b010ad5af822
Revises: 1a31ce608336
Create Date: 2024-09-10 00:37:34.774312

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b010ad5af822'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TABLE item;")
    op.execute('DROP TABLE "user";')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('user', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user', 'name')
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.drop_table('plano')
    op.drop_table('avaliacao')
    op.drop_table('treino_sessao')
    op.drop_table('treino_exercicio')
    op.drop_table('treinador_locais')
    op.drop_table('shape')
    op.drop_table('dieta_refeicoes')
    op.drop_table('treino')
    op.drop_table('treinador')
    op.drop_table('sessao')
    op.drop_table('refeicao')
    op.drop_table('local')
    op.drop_table('exercicio')
    op.drop_table('dieta')
    # ### end Alembic commands ###
