"""migrating

Revision ID: b05af6a7aaba
Revises: 8b254113ca97
Create Date: 2024-09-04 10:12:47.082818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b05af6a7aaba'
down_revision = '8b254113ca97'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TABLE dieta;")
    op.execute("DROP TABLE refeicao;")
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dieta', 'id_ref_manha',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('dieta', 'id_ref_tarde',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('dieta', 'id_ref_noite',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('dieta', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('refeicao', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
'''

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refeicao', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dieta', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dieta', 'id_ref_noite',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('dieta', 'id_ref_tarde',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('dieta', 'id_ref_manha',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
