"""tables changes on user

Revision ID: b1945b39fb15
Revises: 0adb63f4d560
Create Date: 2024-08-30 21:17:31.948260

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b1945b39fb15'
down_revision = '0adb63f4d560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
