"""new

Revision ID: b499e906e1a0
Revises: 4a3e879af350
Create Date: 2024-09-09 23:17:39.090006

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b499e906e1a0'
down_revision = '4a3e879af350'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TABLE plano;")
    op.execute("DROP TABLE dieta_refeicoes;")
    op.execute("DROP TABLE dieta;")
    op.execute("DROP TABLE refeicao;")
    op.execute("DROP TABLE avaliacao;")
    op.execute("DROP TABLE shape;")
    op.execute("DROP TABLE treinador_locais;")
    op.execute("DROP TABLE treinador;")
    op.execute("DROP TABLE local;")
    op.execute("DROP TABLE treino_sessao;")
    op.execute("DROP TABLE treino_exercicio;")
    op.execute("DROP TABLE sessao;")
    op.execute("DROP TABLE treino;")
    op.execute("DROP VIEW exercicios_com_pernas")
    op.execute("DROP VIEW exercicios_cardio")
    op.execute("DROP TABLE exercicio;")
    op.execute('DROP TABLE "user";')
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treino_sessao', type_='foreignkey')
    op.drop_constraint(None, 'treino_sessao', type_='foreignkey')
    op.drop_constraint(None, 'treino_sessao', type_='foreignkey')
    op.drop_constraint(None, 'treino_sessao', type_='foreignkey')
    op.create_foreign_key('treino_sessao_id_treino1_fkey', 'treino_sessao', 'treino', ['id_treino1'], ['id'])
    op.create_foreign_key('treino_sessao_id_treino3_fkey', 'treino_sessao', 'treino', ['id_treino3'], ['id'])
    op.create_foreign_key('treino_sessao_id_treino2_fkey', 'treino_sessao', 'treino', ['id_treino2'], ['id'])
    op.create_foreign_key('treino_sessao_id_sessao_fkey', 'treino_sessao', 'sessao', ['id_sessao'], ['id'])
    op.drop_constraint(None, 'treino_exercicio', type_='foreignkey')
    op.drop_constraint(None, 'treino_exercicio', type_='foreignkey')
    op.create_foreign_key('treino_exercicio_id_treino_fkey', 'treino_exercicio', 'treino', ['id_treino'], ['id'])
    op.create_foreign_key('treino_exercicio_id_exercicio_fkey', 'treino_exercicio', 'exercicio', ['id_exercicio'], ['id'])
    op.drop_constraint(None, 'treinador_locais', type_='foreignkey')
    op.drop_constraint(None, 'treinador_locais', type_='foreignkey')
    op.create_foreign_key('treinador_locais_local_id_fkey', 'treinador_locais', 'local', ['local_id'], ['id'])
    op.create_foreign_key('treinador_locais_treinador_id_fkey', 'treinador_locais', 'treinador', ['treinador_id'], ['id'])
    op.drop_constraint(None, 'shape', type_='foreignkey')
    op.create_foreign_key('shape_usuario_id_fkey', 'shape', 'user', ['usuario_id'], ['id'])
    op.drop_constraint(None, 'plano', type_='foreignkey')
    op.drop_constraint(None, 'plano', type_='foreignkey')
    op.drop_constraint(None, 'plano', type_='foreignkey')
    op.drop_constraint(None, 'plano', type_='foreignkey')
    op.drop_constraint(None, 'plano', type_='foreignkey')
    op.create_foreign_key('plano_id_avaliacao_fkey', 'plano', 'avaliacao', ['id_avaliacao'], ['id'])
    op.create_foreign_key('plano_id_sessao_treino_fkey', 'plano', 'sessao', ['id_sessao_treino'], ['id'])
    op.create_foreign_key('plano_id_treinador_fkey', 'plano', 'treinador', ['id_treinador'], ['id'])
    op.create_foreign_key('plano_id_dieta_fkey', 'plano', 'dieta', ['id_dieta'], ['id'])
    op.create_foreign_key('plano_id_user_fkey', 'plano', 'user', ['id_user'], ['id'])
    op.drop_constraint(None, 'dieta_refeicoes', type_='foreignkey')
    op.drop_constraint(None, 'dieta_refeicoes', type_='foreignkey')
    op.drop_constraint(None, 'dieta_refeicoes', type_='foreignkey')
    op.drop_constraint(None, 'dieta_refeicoes', type_='foreignkey')
    op.create_foreign_key('dieta_refeicoes_id_dieta_fkey', 'dieta_refeicoes', 'dieta', ['id_dieta'], ['id'])
    op.create_foreign_key('dieta_refeicoes_id_ref_noite_fkey', 'dieta_refeicoes', 'refeicao', ['id_ref_noite'], ['id'])
    op.create_foreign_key('dieta_refeicoes_id_ref_tarde_fkey', 'dieta_refeicoes', 'refeicao', ['id_ref_tarde'], ['id'])
    op.create_foreign_key('dieta_refeicoes_id_ref_manha_fkey', 'dieta_refeicoes', 'refeicao', ['id_ref_manha'], ['id'])
    # ### end Alembic commands ###
