"""fks

Revision ID: b55def56e8c1
Revises: 5d731f8e36df
Create Date: 2024-09-07 02:15:01.503341

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b55def56e8c1'
down_revision = '5d731f8e36df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
