"""tables changes on user

Revision ID: b64a895a5c26
Revises: 61bb25bc9766
Create Date: 2024-08-30 21:20:42.416239

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b64a895a5c26'
down_revision = '61bb25bc9766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
