"""lucas changes

Revision ID: bcd51c0f7f9f
Revises: 8434edbda2fb
Create Date: 2024-09-03 18:23:32.484280

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bcd51c0f7f9f'
down_revision = '8434edbda2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refeicao',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('calorias', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dieta',
    sa.Column('id_ref_manha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_ref_tarde', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_ref_noite', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_ref_manha'], ['refeicao.id'], ),
    sa.ForeignKeyConstraint(['id_ref_noite'], ['refeicao.id'], ),
    sa.ForeignKeyConstraint(['id_ref_tarde'], ['refeicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dieta')
    op.drop_table('refeicao')
    # ### end Alembic commands ###
