"""fks

Revision ID: befe50d55582
Revises: 3b5b5fdd8c0e
Create Date: 2024-09-07 08:52:52.961454

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'befe50d55582'
down_revision = '3b5b5fdd8c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plano', 'id_treinador',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_foreign_key(None, 'plano', 'dieta', ['id_dieta'], ['id'])
    op.create_foreign_key(None, 'plano', 'sessao', ['id_sessao_treino'], ['id'])
    op.create_foreign_key(None, 'plano', 'treinador', ['id_treinador'], ['id'])
    op.create_foreign_key(None, 'plano', 'avaliacao', ['id_avaliacao'], ['id'])
    op.drop_column('plano', 'local')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plano', sa.Column('local', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plano', type_='foreignkey')
    op.drop_constraint(None, 'plano', type_='foreignkey')
    op.drop_constraint(None, 'plano', type_='foreignkey')
    op.drop_constraint(None, 'plano', type_='foreignkey')
    op.alter_column('plano', 'id_treinador',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
