"""jp

Revision ID: cb73b46e7266
Revises: 45f5a8cb4f6e
Create Date: 2024-08-29 11:57:35.604421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cb73b46e7266'
down_revision = '45f5a8cb4f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telefone',
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('telefone')
    )
    op.create_table('treinador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('especialidade', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['telefone'], ['telefone.telefone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treinador')
    op.drop_table('telefone')
    # ### end Alembic commands ###
