"""Alter Models

Revision ID: e65d310169f8
Revises: 0040709f8797
Create Date: 2024-09-08 16:57:49.249469

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e65d310169f8'
down_revision = '0040709f8797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('avaliacao_shape_id_fkey', 'avaliacao', type_='foreignkey')
    op.create_foreign_key(None, 'avaliacao', 'shape', ['shape_id'], ['id'], ondelete='CASCADE')
    op.add_column('shape', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shape', 'user', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shape', type_='foreignkey')
    op.drop_column('shape', 'usuario_id')
    op.drop_constraint(None, 'avaliacao', type_='foreignkey')
    op.create_foreign_key('avaliacao_shape_id_fkey', 'avaliacao', 'shape', ['shape_id'], ['id'])
    # ### end Alembic commands ###
