"""tables changes on user

Revision ID: eb0b1e80ca4a
Revises: 0879583c9645
Create Date: 2024-08-30 20:50:15.739190

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eb0b1e80ca4a'
down_revision = '0879583c9645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.add_column('user', sa.Column('birthdate', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('user', 'id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=11),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=11),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('user', 'name')
    op.drop_column('user', 'birthdate')
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    # ### end Alembic commands ###
