"""changes on dml

Revision ID: f6279baf2ef4
Revises: 04a8876ee579
Create Date: 2024-08-30 23:08:57.599952

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f6279baf2ef4'
down_revision = '04a8876ee579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
