"""tables changes on user

Revision ID: fc6c5f6d35f8
Revises: eb0b1e80ca4a
Create Date: 2024-08-30 20:58:04.808848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc6c5f6d35f8'
down_revision = 'eb0b1e80ca4a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('DROP TABLE "user";')
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('user', sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False))
    #op.alter_column('user', 'id',
    #           existing_type=sa.VARCHAR(length=11),
    #           type_=sa.Uuid(),
    #           existing_nullable=False)
    #op.drop_constraint('user_id_key', 'user', type_='unique')
    #op.create_unique_constraint(None, 'user', ['cpf'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_id_key', 'user', ['id'])
    op.alter_column('user', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_column('user', 'cpf')
    # ### end Alembic commands ###
