"""fks

Revision ID: fc8b96cdaadb
Revises: a469e3e11772
Create Date: 2024-09-07 01:47:27.808095

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc8b96cdaadb'
down_revision = 'a469e3e11772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dieta_refeicoes',
    sa.Column('id_dieta', sa.Integer(), nullable=False),
    sa.Column('id_ref_manha', sa.Integer(), nullable=False),
    sa.Column('id_ref_tarde', sa.Integer(), nullable=False),
    sa.Column('id_ref_noite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dieta'], ['dieta.id'], ),
    sa.ForeignKeyConstraint(['id_ref_manha'], ['refeicao.id'], ),
    sa.ForeignKeyConstraint(['id_ref_noite'], ['refeicao.id'], ),
    sa.ForeignKeyConstraint(['id_ref_tarde'], ['refeicao.id'], ),
    sa.PrimaryKeyConstraint('id_dieta', 'id_ref_manha', 'id_ref_tarde', 'id_ref_noite')
    )
    op.drop_constraint('dieta_id_ref_manha_fkey', 'dieta', type_='foreignkey')
    op.drop_constraint('dieta_id_ref_tarde_fkey', 'dieta', type_='foreignkey')
    op.drop_constraint('dieta_id_ref_noite_fkey', 'dieta', type_='foreignkey')
    op.drop_column('dieta', 'id_ref_manha')
    op.drop_column('dieta', 'id_ref_noite')
    op.drop_column('dieta', 'id_ref_tarde')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dieta', sa.Column('id_ref_tarde', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dieta', sa.Column('id_ref_noite', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dieta', sa.Column('id_ref_manha', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dieta_id_ref_noite_fkey', 'dieta', 'refeicao', ['id_ref_noite'], ['id'])
    op.create_foreign_key('dieta_id_ref_tarde_fkey', 'dieta', 'refeicao', ['id_ref_tarde'], ['id'])
    op.create_foreign_key('dieta_id_ref_manha_fkey', 'dieta', 'refeicao', ['id_ref_manha'], ['id'])
    op.drop_table('dieta_refeicoes')
    # ### end Alembic commands ###
